### ISSUE TITLE
Extract cropped face portions from images in the Face_Dataset directory

### ISSUE THREAD

**Issue by eternal-f1ame** [AISocietyIITJ/Face-Tracker#21]
A method to extract and store faces from the live video feed of the webcam is already scripted in create_data.py. The task is to create functions for doing the same but with images from the Face_Dataset directory.
Remember that there should be separate folders for every person's picture, i.e., the structure of the Face_Dataset directory should be retained in the new directory with cropped Faces.

The number of PRs allowed for this issue is 2.

You may take references from google and mediapipe's face detection documentation

**Comment by Akhil-blanc** [comment]
I would like to work on this issue

**Comment by Klord02** [comment]
I would like to work on this issue

**Comment by eternal-f1ame** [comment]
Assigning you both this issue. Make sure to collaborate and complete it correctly,
all the best
