### ISSUE TITLE
Retaining Directory Structure Via Webcam

### ISSUE THREAD

**Issue by eternal-f1ame** [AISocietyIITJ/Face-Tracker#22]
The code for the live webcam data creation in create_data.py is already written in a way that creates a directory structure similar to that of Face_Dataset.
The task is to clean the code, remove redundancy and make necessary changes such that the directory structure of the data generated becomes precisely similar to that of the Face_Dataset.py.

Remember that run_tracker is written preassuming that only one person sits in front of the webcam while creating data. Proceed with the same assumption.
Complete the necessary parts of the documentation.

The number of PRs allowed for this issue is 2
You may thoroughly review the code to understand its work and only then start making changes.

**Comment by Shreyasvaidya** [comment]
Please assign this issue to me.

**Comment by eternal-f1ame** [comment]
Sure, all the best.
