### ISSUE TITLE
Complete Dataset Generation Code

### ISSUE THREAD

**Issue by eternal-f1ame** [AISocietyIITJ/Face-Tracker#27]
In the file data/dataset_generator.py, sections for creating a list of image paths against their class have been left empty.
Write a code under "# map paths to images" in dataset_generator.py to do the abovementioned and add only uncorrupted images to the list. And do so without disturbing the flow of the code, i.e., your code should be modular and easily compatible with the rest of the code in the same file without any need for changes.

The number of PRs for this issue is 2-3, depending on the quality of the code.

**Comment by s-goyal23** [comment]
Please assign this issue to me.

**Comment by yorozuya-2003** [comment]
Please assign this issue to me.

**Comment by eternal-f1ame** [comment]
The issue has been assigned to you both. All the best and happy coding
